### ISSUE TITLE
I am not able to patch split apks. I am using Genymotion Emulator (Android 6.0)

### ISSUE THREAD

**Issue by saurabhlucideus** [NickstaDB/patch-apk#14]
I am getting the below mentioned error. Kindly help how to proceed with it.

Disabling APK splitting in AndroidManifest.xml of base APK.
Traceback (most recent call last):
  File "patch-apk.py", line 620, in <module>
    main()
  File "patch-apk.py", line 29, in main
    apkfile = getTargetAPK(pkgname, apkpaths, tmppath, args.disable_styles_hack)
  File "patch-apk.py", line 238, in getTargetAPK
    return combineSplitAPKs(pkgname, localapks, tmppath, disableStylesHack)
  File "patch-apk.py", line 280, in combineSplitAPKs
    disableApkSplitting(baseapkdir)
  File "patch-apk.py", line 530, in disableApkSplitting
    tree = xml.etree.ElementTree.parse(os.path.join(baseapkdir, "AndroidManifest.xml"))
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp9qt9u409/com.rapido.passenger\r-base/AndroidManifest.xml'

**Comment by NickstaDB** [comment]
Hi @saurabhlucideus, nice finding! Looks like this was an inconsistency between the line separator on your emulator/device and the line separator on your local OS. When `patch-apk` runs `adb shell pm list packages` to verify the package name it splits the output based on `os.linesep` to get the exact package name installed on the device. This is then used to construct temp paths e.g. when the APK is extracted.

In your case `os.linesep` returned `\n` whereas the line separators in the output from `adb shell pm list packages` must have been `\r\n` hence the `\r` in the `FileNotFound` error.

I've fixed this in commit aa8e24f.
