### ISSUE TITLE
Update patch-apk with another network config

### ISSUE THREAD

**Issue by ColtonIdle** [NickstaDB/patch-apk#2]
As per https://github.com/sensepost/objection/issues/347#issuecomment-606735716 it looks like the network config in this script doesn't match what's used in objection, but the one in objection allows system certs and so it works in the usual case of not having ssl proxying setup yet.

**Comment by NickstaDB** [comment]
Already implemented earlier :)

https://github.com/NickstaDB/patch-apk/commit/19330e76168ff9d1a06983a93f72164955d20d4c
