### ISSUE TITLE
Unable to patch any apk

### ISSUE THREAD

**Issue by jim-at-jibba** [NickstaDB/patch-apk#25]
When trying to patch any apk I get the following error.

Running on a Mac with Genymotion

```
python3 patch-apk.py covid
Getting APK path(s) for package: com.joinzoe.covid_zoe
[+] APK path: /data/app/com.joinzoe.covid_zoe-pZTJamGy2NUI3PqezUGgOQ==/base.apk

Pulling APK file(s) from device.
[+] Pulling: com.joinzoe.covid_zoe-base.apk

Patching com.joinzoe.covid_zoe-base.apk with objection.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/c2/6_9lph710p9_m5kjkrt4507h0000gn/T/tmp93g0gov_/com.joinzoe.covid_zoe-base.objection.apk' -> '/var/folders/c2/6_9lph710p9_m5kjkrt4507h0000gn/T/tmp93g0gov_/com.joinzoe.covid_zoe-base.apk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "patch-apk.py", line 633, in <module>
    main()
  File "patch-apk.py", line 49, in main
    shutil.move(apkfile[:-4] + ".objection.apk", apkfile)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 805, in move
    copy_function(src, real_dst)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/c2/6_9lph710p9_m5kjkrt4507h0000gn/T/tmp93g0gov_/com.joinzoe.covid_zoe-base.objection.apk'
```

Thanks

**Comment by NickstaDB** [comment]
This may have been an issue with detecting the installed version of objection. Previously the `getObjectionVersion()` method was running the `objection version` command, splitting the output on the string `": "`, and treating the right-hand side of that as the version number.

When objection is outdated, however, the `objection version` command output includes the string `"Upgrade with: pip3 install objection --upgrade"`, which led to `getObjectionVersion()` returning `pip3 install objection --upgrade`. This was considered to be less than `1.9.3`, causing objection to be run without the `--ignore-nativelibs` flag that's required with `--skip-resources` for objection >= 1.9.3.

Hopefully the latest commit resolves the issue. I'll check with the specific app you were looking at later and close this issue if it appears to be working. Let me know if it's still failing for you though.

**Comment by jim-at-jibba** [comment]
Hey Nick,

you were right. Updating the script and objection seemed to have fixed the issue. Works like a dream

Thank you so much for fixing

**Comment by NickstaDB** [comment]
Brill - glad it's working now!
