### ISSUE TITLE
Unable to adp pull due to file path

### ISSUE THREAD

**Issue by 036** [NickstaDB/patch-apk#3]
Running adb shell pm path shows two apks that need pulling 

`package:/data/app/com.n3twork.legendary-baeXvaHcnKxinZnGogrkMA==/base.apk
package:/data/app/com.n3twork.legendary-baeXvaHcnKxinZnGogrkMA==/split_config.arm64_v8a.apk`

This is the output of running the patch-apk script

```
python patch-apk.py com.n3twork.legendary                                                                                                                                                                                             Getting APK path(s) for package: com.n3twork.legendary
[+] APK path: /data/app/com.n3twork.legendary-baeXvaHcnKxinZnGogrkMA==/base.apk
[+] APK path: /data/app/com.n3twork.legendary-baeXvaHcnKxinZnGogrkMA==/split_config.arm64_v8a.apk

Pulling APK file(s) from device.
[+] Pulling: com.n3twork.legendary-/data/app/com.n3twork.legendary-baeXvaHcnKxinZnGogrkMA==/base.apk
Error: Failed to run 'adb pull /data/app/com.n3twork.legendary-baeXvaHcnKxinZnGogrkMA==/base.apk C:\Users\rob\AppData\Local\Temp\tmpycwez99m\com.n3twork.legendary-/data/app/com.n3twork.legendary-baeXvaHcnKxinZnGogrkMA==/base.apk'.
Run with --debug-output for more information.
```

When running adp pull manually with the same parameters the error shows it cannot create the file/directory

```
adb: error: cannot create file/directory 'C:\Users\rob\AppData\Local\Temp\tmpycwez99m\com.n3twork.legendary-/data/app/com.n3twork.legendary-baeXvaHcnKxinZnGogrkMA==/base.apk': No such file or directory
```

I suspect this is due to the naming/path of the package however I'm not entirely sure.

**Comment by NickstaDB** [comment]
Cheers for reporting this! The script was using the local path separator to split the remote path and as a result b0rking when run from Windows.

This should be fixed in the latest commit https://github.com/NickstaDB/patch-apk/commit/9a1fc17151fd353b187110b15f8c275952e2ae0c. Let me know if you have any further issues though!
