### ISSUE TITLE
Destroys the freenet FUNK App

### ISSUE THREAD

**Issue by kmifka** [NickstaDB/patch-apk#8]
When I try to patch the freenet FUNK app, everything in the tool works fine, but the patched app can't be opened anymore and only shows a white screen.

Maybe the problem is simply with Objection, then the ticket can be closed of course.

**Comment by NickstaDB** [comment]
Hi @kmifka, this is normal behaviour. See https://github.com/sensepost/objection/wiki/Early-Instrumentation.

Assuming you don't need to do any early instrumentation, simply run `objection explore` to connect to the objection agent and resume the application's normal execution.
